---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: devops
spec:
  selector:
    app: jenkins
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deploy
  namespace: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      securityContext:
            fsGroup: 1000
            runAsUser: 1000
      serviceAccountName: jenkins-admin
      nodeSelector:
        jenkins: "true"
      containers:
      - name: jenkins
        image: jenkins/jenkins:lts-jdk17
        resources:
          limits:
            memory: "1500Mi"
            cpu: "2000m"
          requests:
            memory: "500Mi"
            cpu: "500m"
        ports:
        - name: httpport
          containerPort: 8080
        - name: jnlpport
          containerPort: 50000
        livenessProbe:
          httpGet:
            path: "/login"
            port: 8080
          initialDelaySeconds: 90
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: "/login"
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        volumeMounts:
        - name: data
          mountPath: /var/jenkins_home
        - name: kubectl
          mountPath: /usr/bin/kubectl
        - name: docker
          mountPath: /run/docker.sock
        - name: docker-home
          mountPath: /usr/bin/docker
        - name: daemon
          mountPath: /etc/docker/daemon.json
          subPath: daemon.json
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: jenkins-pvc
      - name: kubectl
        hostPath:
          path: /usr/bin/kubectl
      - name: docker
        hostPath:
          path: /run/docker.sock
      - name: docker-home
        hostPath:
          path: /usr/bin/docker
      - name: daemon
        hostPath:
          path: /etc/docker/
