services:
  nacos:
    image: nacos/nacos-server:v2.3.2
    hostname: nacos
    container_name: nacos
    ports:
    - "8848:8848"
    - "9848:9848"
    environment:
      MODE: standalone
    healthcheck:
      test: curl http://localhost:8848/nacos
      interval: 5s
      timeout: 10s
      retries: 10
  mysql-cloud:
    hostname: mysql-cloud
    container_name: mysql-cloud
    build: ./mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 5s
      timeout: 10s
      retries: 10
  init-spring-cloud-test:
    build: .
  oauth2-server:
    build: ./oauth2-server
    hostname: oauth2-server
    container_name: oauth2-server
    ports:
    - "9000:9000"
    depends_on:
      init-spring-cloud-test:
        condition: service_completed_successfully
      nacos:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "localhost:9000/.well-known/openid-configuration" ]
      interval: 5s
      timeout: 10s
      retries: 10
    restart: always
  api-gateway:
    build: ./api-gateway
    hostname: api-gateway
    container_name: api-gateway
    ports:
    - "8080:8080"
    depends_on:
      init-spring-cloud-test:
        condition: service_completed_successfully
      nacos:
        condition: service_healthy
      oauth2-server:
        condition:  service_healthy
    restart: always
  user-service:
    build: ./user-service
    hostname: user-service
    container_name: user-service
    ports:
    - "8081:8081"
    depends_on:
      init-spring-cloud-test:
        condition: service_completed_successfully
      nacos:
        condition: service_healthy
    restart: always
  order-service:
    build: ./order-service
    hostname: order-service
    container_name: order-service
    ports:
    - "8091:8091"
    depends_on:
      init-spring-cloud-test:
        condition: service_completed_successfully
      nacos:
        condition: service_healthy
    restart: always