const ActionTaskName = {
    START_MAIN_FLOW: 'START_MAIN_FLOW',
    NEXT: 'NEXT',
    BACK: 'BACK',
    CANCEL: 'CANCEL',
    SET_CALLBACK_RESULT: 'SET_CALLBACK_RESULT',
    GET_CACHE: 'GET_CACHE',
    GET_CACHE_RESPONSE: 'GET_CACHE_RESPONSE',
    CLOSE_POPUP_RESPONSE: 'CLOSE_POPUP_RESPONSE'
}

export default ActionTaskName