spring:
  application:
    name: batch
  profiles:
    active:
    - local
  jpa:
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${com.zhou.mysql.ip}:3306/batchdb?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  kafka:
    bootstrap-servers: ${com.zhou.kafka.ip}:${com.zhou.kafka.port}
    template:
      default-topic: test-topic
    consumer:
      group-id: test-service
      enable-auto-commit: false
      auto-offset-reset: earliest
      max-poll-records: 50
logging:
  level:
    com.zhou: debug
    org.hibernate: debug