services:
  mysql-mybatis:
    hostname: mysql-mybatis
    container_name: mysql-mybatis
    build: ./mysql
    ports:
    - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 5s
      timeout: 10s
      retries: 10
  mybatis-test:
    build: ./mybatis-test
    hostname: mybatis-test
    container_name: mybatis-test
    ports:
    - "8080:8080"
    depends_on:
    - mysql-mybatis