services:
  postgres:
    hostname: postgres
    container_name: postgres
    build: ./postgres
    ports:
    - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U postgres -d testdb'"]
      interval: 5s
      timeout: 10s
      retries: 10
  postgres-type-test:
      hostname: postgres-type-test
      container_name: postgres-type-test
      build: ./postgres-type-test
      ports:
      - "8080:8080"
      depends_on:
      - postgres
      restart: always