com:
  zhou:
    datasource:
      jdbcUrl: jdbc:postgresql://localhost:5432/testdb?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
      driverClassName: org.postgresql.Driver
      username: postgres
      password: root