apiVersion: v1
kind: Service
metadata:
  name: sonarqube-service
  namespace: devops
  labels:
    app: sonarqube
spec:
  type: NodePort
  ports:
  - name: sonarqube
    port: 9000
    targetPort: 9000
    protocol: TCP
  selector:
    app: sonarqube
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube-deploy
  namespace: devops
  labels:
    app: sonarqube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      initContainers:
      - name: init-sysctl
        image: busybox:1.36.1-glibc
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      containers:
      - name: sonarqube
        image: sonarqube:9.9.6-developer
        ports:
        - containerPort: 9000
        env:
        - name: SONARQUBE_JDBC_USERNAME
          value: "test"
        - name: SONARQUBE_JDBC_PASSWORD
          value: "test"
        - name: SONARQUBE_JDBC_URL
          value: "jdbc:postgresql://postgres-sonar-service:5432/sonarDB"
        livenessProbe:
          httpGet: 
            path: /sessions/new
            port: 9000
          initialDelaySeconds: 60
          periodSeconds: 60
        readinessProbe:
          httpGet:
            path: /sessions/new
            port: 9000
          initialDelaySeconds: 60
          periodSeconds: 30
          failureThreshold: 6
        volumeMounts:
        - name: data
          mountPath: /opt/sonarqube/conf
        - name: data
          mountPath: /opt/sonarqube/data
        - name: data
          mountPath: /opt/sonarqube/extensions
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: sonarqube-pvc
