apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: kube-logging
  labels:
    k8s-app: filebeat
data:
  filebeat.yml: |-
    filebeat.inputs:
    - type: log
      enable: true
      paths:
      - "/var/log/test/*.log"
      processors:
      - add_kubernetes_metadata:
          host: ${NODE_NAME}
          matchers:
          - logs_path:
              logs_path: "/var/log/test/"
    output.logstash:
      hosts: ["logstash-service:5044"]
      enable: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: filebeat-service-account
  namespace: kube-logging
  labels:
    k8s-app: filebeat
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: filebeat-cluster-role
  labels:
    k8s-app: filebeat
rules:
- apiGroups:
  - ""
  resources:
  - "namespaces"
  - "pods"
  - "nodes"
  verbs:
  - "get"
  - "watch"
  - "list"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: filebeat-cluster-role-binding
  namespace: kube-logging 
subjects:
- kind: ServiceAccount
  name: filebeat-service-account
  namespace: kube-logging
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: filebeat-cluster-role
  apiGroup: ""
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: filebeat-daemonset
  namespace: kube-logging
  labels:
    k8s-app: filebeat
spec:
  selector:
    matchLabels:
      k8s-app: filebeat
  template:
    metadata:
      labels:
        k8s-app: filebeat
    spec:
      serviceAccountName: filebeat-service-account
      terminationGracePeriodSeconds: 30
      containers:
      - name: filebeat
        image: docker.elastic.co/beats/filebeat:8.14.3
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        # - name: ELASTICSEARCH_HOST
        #   value: elasticsearch-logging
        # - name: ELASTICSEARCH_PORT
        #   value: "9200"
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
          requests:
            cpu: 500m
            memory: 100Mi
        args:
        - "-c"
        - "/etc/config/filebeat.yml"
        - "-e"
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: config
          mountPath: "/etc/config/"
        - name: data
          mountPath: /usr/share/filebeat/data
        - name: varlog
          mountPath: "/var/log/test/"
          readOnly: true
      volumes:
      - name: config
        configMap:
          defaultMode: 0600
          name: filebeat-config
      - name: varlog
        hostPath: 
          path: "/var/log/test/"
      - name: data
        hostPath:
          path: "/data/filebeat-data"
          type: DirectoryOrCreate
      # tolerations:
      # - effect: NoSchedule
      #   operator: Exists
